apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.name" . }}
  labels:
    {{- include ".Values.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include ".Values.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include ".Values.labels" . | nindent 8 }}
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: {{ .Values.image.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}