apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.name" . }}
  labels:
    {{- include ".Values.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
  selector:
    {{- include ".Values.labels" . | nindent 4 }}