# Default values for the chart

replicaCount: 1
image:
  name: nodejs-aks-helm
  repository: circlecihelmtutorial.azurecr.io/nodejs-aks-helm
  tag: 319e0ef0cffe0d69cbaf3b4654f859b514882ede
service:
  type: LoadBalancer
  port: 80
  containerPort: 1337
