# Default values for the chart

replicaCount: 1
image:
  name: nodejs-aks-helm
  repository: circlecihelmtutorial.azurecr.io/nodejs-aks-helm
  tag: eda9c9c72b56e38ef78365ff0657001714bb52b3
service:
  type: LoadBalancer
  port: 80
  containerPort: 1337
