# Default values for the chart

replicaCount: 1
image:
  name: nodejs-aks-helm
  repository: circlecihelmtutorial.azurecr.io/nodejs-aks-helm
  tag: 93a90f31f80641329a062d02d3b62e7c02fe0132
service:
  type: LoadBalancer
  port: 80
  containerPort: 1337
