# Default values for the chart

replicaCount: 1

image:
  name: nodejs-aks-helm
  repository: docker.io/avik6028/nodejs-aks-helm
  tag: latest

service:
  type: LoadBalancer
  port: 80
  containerPort: 1337
