# Default values for the chart

replicaCount: 1
image:
  name: nodejs-aks-helm
  repository: circlecihelmtutorial.azurecr.io/nodejs-aks-helm
  tag: 23903e0efb911dc77f9317511a90f2ce8d61f385
service:
  type: LoadBalancer
  port: 80
  containerPort: 1337
